export {default as Nav} from './Nav'
export {default as Suggestions} from './Suggestions'
export {default as Blogs} from './Blogs'
export {default as Footer} from './Footer'
export {default as Topics} from './Topics'